name: vafdb
channels:
  - defaults
  - conda-forge
  - anaconda
dependencies:
  # sudo apt-get install postgresql postgresql-contrib
  # sudo apt-get install rabbitmq-server
  - gunicorn
  - pybind11
  - pip
  - pip:
    - psycopg2
    - django
    - djangorestframework
    - django-filter
    - requests
    - pysam
    - numpy
    - pandas
    - git+https://github.com/tombch/basecount@0315dbbf1f8eaf94e85fcc4c3c468b346705dbff
    - celery
