name: vafdb
channels:
  - defaults
  - conda-forge
  - anaconda
dependencies:
  # sudo apt-get install postgresql postgresql-contrib
  # sudo apt-get install rabbitmq-server
  - gunicorn
  - pybind11
  - pip
  - pip:
    - psycopg2
    - django
    - djangorestframework
    - requests
    - pysam
    - numpy
    - pandas
    - git+https://github.com/tombch/basecount@cdf987701ca0c075bad0251b9f4c949c74a4517c
    - celery
