name: vafdb
channels:
  - defaults
dependencies:
  - gunicorn
  - pip
  - pip:
    - django
    - djangorestframework
    - django-filter
    - requests
    - pandas
    - celery
    - biopython
    - maptide
    - django-query-tools