name: vafdb
channels:
  - defaults
dependencies:
  # postgresql
  # postgresql-contrib
  # rabbitmq-server
  - gunicorn
  - pybind11
  - pip
  - pip:
    - psycopg2
    - django
    - djangorestframework
    - django-filter
    - requests
    - pysam
    - numpy
    - pandas
    - celery
    - biopython
    - git+https://github.com/tombch/basecount.git#egg=basecount
