# Generated by Django 4.0.5 on 2022-06-16 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetadataRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pathogen', models.CharField(max_length=100)),
                ('central_sample_id', models.CharField(max_length=100)),
                ('run_name', models.CharField(max_length=100)),
                ('published_name', models.CharField(max_length=100, unique=True)),
                ('collection_date', models.DateField()),
                ('published_date', models.DateField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('num_vafs', models.IntegerField()),
                ('fasta_path', models.CharField(max_length=500)),
                ('bam_path', models.TextField(max_length=500)),
                ('lineage', models.CharField(max_length=100)),
                ('primer_scheme', models.CharField(max_length=100)),
            ],
            options={
                'unique_together': {('central_sample_id', 'run_name')},
            },
        ),
        migrations.CreateModel(
            name='VAFRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100)),
                ('position', models.IntegerField()),
                ('coverage', models.IntegerField()),
                ('num_a', models.IntegerField()),
                ('num_c', models.IntegerField()),
                ('num_g', models.IntegerField()),
                ('num_t', models.IntegerField()),
                ('num_ds', models.IntegerField()),
                ('metadata_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vafs', to='base.metadatarecord')),
            ],
            options={
                'unique_together': {('metadata_record', 'reference', 'position')},
            },
        ),
    ]
